# Generated by Django 4.2 on 2024-10-08 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/no_profile.png', upload_to='users/'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Номер телефона должен состоять только из цифр')], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.IntegerField(default=0, verbose_name='Количество публикаций'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='О себе (кратко)'),
        ),
    ]
