# Generated by Django 4.2 on 2024-10-05 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paid_content_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='Сессия')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paid_content_app.post', verbose_name='Публикация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Приобретенная публикация',
                'verbose_name_plural': 'Приобретенные публикации',
            },
        ),
    ]
